name: Sindhgatta2020
channels:
  - conda-forge
  - defaults
dependencies:
  - keras=2.4.3
  - keras-preprocessing=1.1.2
  - scikit-learn=0.23.2
  - scipy=1.8.1
  - pandas=1.4.4
  - numpy=1.19.5
  - networkx=3.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - matplotlib-inline=0.1.6
  - defusedxml=0.7.1
  - libxml2=2.11.5
  - nltk=3.8.1
  - jellyfish=1.0.0
  - platformdirs=3.10.0
  - typer=0.9.0
  - pip:
    - pm4py==2.7.5
